### ISSUE TITLE
The name of the catalog is None

### ISSUE THREAD

**Issue by st3107** [bluesky/databroker#631]
I made a python package of a database of msgpack files. Below is the repo of the package.

https://github.com/st3107/dbexample

I installed the package and I can access the databroker catalog. However, I found that the name of the calalog is None. Below is how I access the catalog.

```
In [1]: from databroker import catalog

In [2]: db = catalog['example']

In [3]: print(type(db.name))
<class 'NoneType'>
```
I would like to db to have the same name as the name of module in setup.py. I wonder how I can do that.

Also, I wonder if the python package distribtued database has name of ``None`` is a designed feature or if it is something wrong in my configuration.

Thank you.

**Comment by danielballan** [comment]
Thanks for the report @st3107. This looks like a bug in `databroker` or `intake`. Your `setup.py` looks correct to me, and you are right to expect `db.name` to match the name in `setup.py`. The bug would be somewhere in here, I think.

https://github.com/bluesky/databroker/blob/f6806ecfd78c9bb3b248bf90e3696f2cd7459fa7/databroker/discovery.py#L9-L64

Nothing jumps out at me immediately. I can investigate after the holidays, unless someone gets to it first.

**Comment by prjemian** [comment]
I'm getting [the same behavior](https://github.com/BCDA-APS/apstools/issues/468#issuecomment-759596594) and have identified it when a Broker-style yaml file is opened with `databroker.catalog`.  Here is my example:

---

It is observed that when `Broker`-style yaml files are opened with `db = databroker.catalog["db_name"]` (for example), the configuration name reported by `db.name` is `None` instead of `db_name`.  This should be addressed in upstream *databroker* package.

```python
In [222]: mdb.name

In [223]: mdb2 = databroker.Broker.named("mongodb_config")

In [224]: mdb2.name
Out[224]: 'mongodb_config'

In [225]: mdb = databroker.catalog["mongodb_config"]

In [226]: mdb.name

```

**Comment by prjemian** [comment]
Also:

```python
In [227]: mdb.v1.name

In [228]: mdb2.v1.name
Out[228]: 'mongodb_config'

In [229]: mdb2.v2.name
Out[229]: 'mongodb_config'

In [230]: mdb.v2.name

```

**Comment by prjemian** [comment]
BTW, my `mongodb_config.yml` file here is:

```yaml
description: 'heavyweight shared database'
metadatastore:
    module: 'databroker.headersource.mongo'
    class: 'MDS'
    config:
        host: 'localhost'
        port: 27017
        database: 'metadatastore-production-v1'
        timezone: 'US/Central'
assets:
    module: 'databroker.assets.mongo'
    class: 'Registry'
    config:
        host: 'localhost'
        port: 27017
        database: 'filestore-production-v1'
```
